=== MeinAccount/com.mrk.wcf.tracking/XSD/trackingGoal.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install or delete tracking goals. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://github.com" targetNamespace="https://github.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="http://www.woltlab.com/XSD/maelstrom/types.xsd" />
	
	<!-- data node -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element type -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="goal" type="trackingGoal" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- delete element type -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="goal" type="trackingGoal" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- tracking goal element type -->
	<xs:complexType name="trackingGoal">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar" minOccurs="0" />
			<xs:element name="description" type="woltlab_varchar" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== MeinAccount/com.mrk.wcf.tracking/trackingGoal.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.github.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com https://github.com/MeinAccount/com.mrk.wcf.tracking/raw/master/XSD/trackingGoal.xsd">
	<import>
		<!-- com.woltlab.wcf -->
		<goal>
			<name>com.woltlab.wcf.login</name>
			<description><![CDATA[WCF Login]]></description>
			<description language="de"><![CDATA[WCF Anmeldung]]></description>
		</goal>
		<goal>
			<name>com.woltlab.wcf.register</name>
			<description><![CDATA[WCF Register]]></description>
			<description language="de"><![CDATA[WCF Registrierung]]></description>
		</goal>
	</import>
</data>
